### ISSUE TITLE
Interactive self help.

### ISSUE THREAD

**Issue by NickOcaz** [NickOcaz/Mind-Your-Mind#10]
**User story:**

As visitor, I want to interact with animated elements of the website.

**Accepted criteria:**

- [ ] Flip cards to animate the when the tips cards have been. Image representing a tip on one side and information regarding this on the other.

**Task:**

- [ ] Adapt Tip section cards with. 

- [ ] CSS animation to these card.
