### ISSUE TITLE
Footer/ Social links

### ISSUE THREAD

**Issue by NickOcaz** [NickOcaz/Mind-Your-Mind#11]
**User story.**

As a visitor, I would like to follow on social media to keep up to date and explore more about Mind Your Mind.

**Accepted criteria.**

- [x] A visible Footer with social links to Facebook, Instagram and Twitter.

**Tasks.**

- [x] Create a footer for the bottom of the webpage.
- [ ] Add links
- [x] Utilise FontAwesome for link icons.
