### ISSUE TITLE
Events

### ISSUE THREAD

**Issue by NickOcaz** [NickOcaz/Mind-Your-Mind#12]
**User story,**

As a visitor, I would like to know what organized events are coming up that I may be interested in.

**Accepted criteria.**

- [ ] A calendar of upcoming  events relating to Mind Your Mind and other organisations.

**Tasks.**

Card containing dropdown menu upcoming dates, location and brief details of the events. 

- [ ] Implement a drop down menu.

- [ ] Each event linked to our own further information of the event or to external organisers. 

- [ ] Next event visible on the menu with a hint to view more in the menu.
