### ISSUE TITLE
Users stories

### ISSUE THREAD

**Issue by NickOcaz** [NickOcaz/Mind-Your-Mind#13]
**User story.**

As a visitor, I want to read about other peoples positive experiences with mental health.

**Accepted criteria.**

Add information to enquire if message submitted via the contact form is one that the user would like to have published on our page.

- [ ]Maintain User confidentiality and inform user of this via the form to be filled. 
  
- [ ]A link from the homepage to a designated page on others users experiences.

- [ ]A page dedicated to these publications.

**Tasks.**

- [ ] Update form with a tick box to identify if the message is to be published once screened for content.

- [ ] Inform user on the form that their details will be kept confidential.

- [ ] Create confidentiality policy and link to this via the form,

- [ ] Add page designated for these publications maintaining the overall feel of the website
