### ISSUE TITLE
User friendly navigation / Responsive design

### ISSUE THREAD

**Issue by NickOcaz** [NickOcaz/Mind-Your-Mind#3]
User story:

 As a first time visitor I want to access a friendly design that is responsive so that I can access information quickly

**Acceptance criteria**

- [x] A fully responsive website across various screen sizes
- [x] Site layout and navigation are intuitive, allowing easy access to different sections.

**Tasks**

- [x] Apply responsive design principles using Bootstrap and Flex to ensure the website is accessible on various devices.
- [x] Arrange the site layout and navigation based on best practices, ensuring all key sections and pages are easily accessible.
