### ISSUE TITLE
Hero section - High quality images and information

### ISSUE THREAD

**Issue by NickOcaz** [NickOcaz/Mind-Your-Mind#5]
**User Story** 
 
- As a user, I want to understand the purpose of the website immediately upon arrival so that I can get a visual understanding of the services offered. I don't want to see image that may trigger previous trauma.

**Acceptance Criteria**
- [x] The homepage features a hero image with a flex table overlay. On one side of the hero image will have carousal off affirmations making the site welcoming.  These affirmations automatically rotate.

- [x] The right hand-side of this hero section will have positive images (Possibly rotating like the affirmations or as part of the affirmations rotation.

- [x] High-quality positive images of people from a variety of backgrounds.

- [x] Engaging descriptions

- [x] The homepage layout in an uncluttered.

- [x] All images to maintain a positive vibe.

**Tasks**

- [x] Design and implement a homepage layout that prominently features the images and descriptions.
 
- [x] Collect images for all essential elements, 
                           - [x]  Heroes - x3,
                           - [x]  Hero background
                           - [ ]  Tips - x3
                           - [ ]  Logo - (Title, about us)
                           - [ ]  Resources -  3-6                      

- [ ] Integrate 'Call to Action' for a contact us in a grid for the hero section.

- [ ] A list of several Affirmations that uplift visitors and embed these.
