### ISSUE TITLE
Self help tips

### ISSUE THREAD

**Issue by NickOcaz** [NickOcaz/Mind-Your-Mind#7]
**User Story:**

As a visitor, I want to quickly see an overview of the self-help tips offered so that I can determine if these meet my needs.

**Acceptance Criteria:**

- [x] A section of cards dedicated to tips for self-help relating to dealing with depression and/or anxiety.

- [x] Each card is represented by an image, a title, and a short description.

- [x] The cards are displayed in a responsive grid layout.

**Tasks:**

- [x] Create a section for services with a heading.

- [x] Display each service using cards that include an image, title, and description.

- [x] Ensure the layout adjusts responsively on different screen sizes.
- [x] Include a link from the navbar.
- [x] Duplicate for recognising symptoms section
