### ISSUE TITLE
About us

### ISSUE THREAD

**Issue by NickOcaz** [NickOcaz/Mind-Your-Mind#9]
**User story:**

As a first time visitor, I want to understand what the website is about quickly so that I will know if I am interested in what is on offer and potentially explore more.

**Acceptance criteria.**

- [x] Information about our aims is clear and brief so not to overwhelm visitor.

**Tasks.**

- [x] Create a short story for Mind Your Mind that is easy to understand so they can see clearly why they may like our service.
- [x] Create a layout under the hero section that is responsive. 
- [x] Include logo.
- [x] Link from menu.
